# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatesMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('datesmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.DatesMixin')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            bases=('search.datesmixin',),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('datesmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.DatesMixin')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=('search.datesmixin',),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.BookCategory'),
        ),
    ]
